### ISSUE TITLE
Connect Airsim with ROS

### ISSUE THREAD

**Issue by Shreeyak** [DIYRobocars-BLR/arm_arc#6]

**Comment by aravindk2604** [comment]
[AirSim ROS Wrapper Python](https://github.com/Mayankm96/airsim_ros_wrapper)
Spoke to the developer of this package and he seems to have got the connection between AirSim and ROS working with the latest releases from Microsoft and Unreal.
It is in Python and I'm not that familiar. Apparently his C++ version wrapper conforms to the old release of AirSim and no longer has support from Microsoft. I've been trying to get that C++ version build with the latest release but running into some weird fpermissive errors and still looking into it.

Meanwhile anyone of you comfortable with Python can test this package, if time permits.

**Comment by Shreeyak** [comment]
Awesome work, Aravind. Is there any documentation of the python API? How
does one get started?

**Comment by aravindk2604** [comment]
Sadly not much documentation is out there.
Step 1. Download and build Unreal 4.18
Step 2. Download and build AirSim v1.2 (using default clang++) natively. Which means follow the instructions on the AirSim official repo to build it on Linux.
Step 3. Run Unreal and open a sample environment in Airsim
Step 4. Download the ROS wrapper pkg i mentioned in the previous comment and catkin_make it under a workspace. The launch instructions will help run the pkg. But this will be for a quadcopter. We can change to car once we get this pkg running as is

**Comment by aravindk2604** [comment]
[The repo that establishes connection and publishes Images](https://github.com/DIYRobocars-BLR/publishAirsimImgs)
